site_name: FUXA Documentation
site_url: https://frangoteam.github.io/FUXA/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      logo: assets/logo.svg

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      logo: assets/logo.svg

nav:
  - Home: index.md
  - Live Demo: https://frangoteam.github.io/
  - Getting Started:
      - Installing and Running: Installing-and-Running.md
  - HowTo:
      - Devices and Tags: HowTo-Devices-and-Tags.md
      - Bind Controls: HowTo-bind-Controls.md
      - Chart Control: HowTo-Chart-Control.md
      - UI Layout: HowTo-UI-Layout.md
      - Setup Alarms: HowTo-setup-Alarms.md
      - Define Shapes: HowTo-define-Shapes.md
      - Animate Pipe: HowTo-animate-Pipe.md
      - Scheduler: HowTo-Scheduler.md
      - Node-RED: HowTo-Node-Red.md
      - Save/Load Project: HowTo-save-load-Project.md
      - Configure Events: HowTo-configure-events.md
      - Use Same View: HowTo-use-same-view.md
      - Configure Script: HowTo-configure-Script.md
      - ODBC: HowTo-ODBC.md
      - Widgets: HowTo-Widgets.md
      - WebSockets: HowTo-WebSockets.md
  - Settings: Settings.md
  - Tips and Tricks: Tips-and-Tricks.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frangoteam/FUXA
      name: GitHub Repository

    - icon: fontawesome/brands/discord
      link: https://discord.gg/WZhxz9uHh4
      name: Discord Community

copyright: >
  Powered by <a href="https://frangoteam.org" target="_blank" rel="noopener">
  <strong>frangoteam</strong></a>